name: Scientific Computing CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install uv (Package Manager)
        uses: astral-sh/setup-uv@v3
        with:
          version: 'latest'

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Run Tests
        run: uv run pytest


      - name: Upload results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: simulation-results
          path: outputs/figures/